version: "3.9"

services:
  app:
    build: .
    container_name: rails_app
    command: bash -c "bundle exec rails db:create db:migrate && bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/user_content_api
  db:
    image: postgres:14
    container_name: rails_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: user_content_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5433"

volumes:
  pg_data:
  bundle_cache:
